import { LyriaStylePreset } from "./lyriaTypes";

export const LYRIA_STYLE_PRESETS: LyriaStylePreset[] = [
  {
    id: "pure_harmony",
    name: "Pure Harmony (Default)",
    genreCategory: "Educational",
    description: "Rất tối giản, tập trung vào tiếng Piano/Electric Piano và Bass nhẹ để làm nổi bật cấu trúc hợp âm.",
    instrumentation: ["electric piano", "upright piano", "simple bass", "subtle synth pad", "minimal percussion"],
    defaultTempoRange: [70, 120],
    moodKeywords: ["clear", "educational", "pure", "transparent", "focused"],
  },
  {
    id: "jpop",
    name: "J-Pop / Anime",
    genreCategory: "Pop",
    description: "Âm hưởng J-Pop / Anime sôi động, hợp âm mở rộng rực rỡ cảm xúc.",
    instrumentation: ["clean electric guitar", "warm piano", "bright synth pad", "driving bass", "tight drums"],
    defaultTempoRange: [125, 160],
    moodKeywords: ["uplifting", "emotional", "bright", "energetic", "melodic"],
  },
  {
    id: "citypop",
    name: "City Pop",
    genreCategory: "Pop / Retro",
    description: "Nhạc Nhật Bản thập niên 80 hoài niệm, sang trọng và nhịp nhàng.",
    instrumentation: ["vintage Fender Rhodes", "brass synth", "funk bass", "chime guitar", "retro drum machine"],
    defaultTempoRange: [110, 128],
    moodKeywords: ["nostalgic", "sophisticated", "groovy", "warm", "stylish"],
  },
  {
    id: "vpop",
    name: "V-Pop Indie & Ballad",
    genreCategory: "Indie / Ballad",
    description: "Nhẹ nhàng như quán cafe góc phố, guitar mộc mạc và piano đầm ấm.",
    instrumentation: ["acoustic guitar", "soft upright piano", "warm cello pad", "light brush snare"],
    defaultTempoRange: [70, 95],
    moodKeywords: ["intimate", "gentle", "melancholic", "warm", "peaceful"],
  },
  {
    id: "neosoul",
    name: "Neo-Soul / R&B",
    genreCategory: "R&B",
    description: "Tiếng Rhodes mở rộng 9th/11th mượt mà, rải nốt màu sắc lướt nhẹ.",
    instrumentation: ["Fender Rhodes", "deep sub bass", "vinyl crackle texture", "mellow guitar leads", "layback rimshot beat"],
    defaultTempoRange: [75, 95],
    moodKeywords: ["smooth", "soulful", "laid-back", "sensual", "warm"],
  },
  {
    id: "jazz",
    name: "Jazz Standard",
    genreCategory: "Jazz",
    description: "Giai điệu Swing kinh điển, tiêng Bass gõ nhịp và hòa âm 7th/9th/13th phong phú.",
    instrumentation: ["grand piano", "upright walking bass", "brushed drums", "subtle tenor sax pad"],
    defaultTempoRange: [100, 170],
    moodKeywords: ["sophisticated", "swinging", "rich", "expressive", "classic"],
  },
  {
    id: "lofi",
    name: "Lo-Fi Chillhop",
    genreCategory: "Chill",
    description: "Âm thanh ấm áp thư giãn, phím đàn xước nhẹ đĩa than, giai điệu nhẹ nhàng.",
    instrumentation: ["muffled electric piano", "tape saturation warm bass", "dusted hiphop beat", "ambient vinyl noise"],
    defaultTempoRange: [70, 90],
    moodKeywords: ["cozy", "relaxing", "nostalgic", "mellow", "lo-fi"],
  },
  {
    id: "cinematic",
    name: "Cinematic Orchestral",
    genreCategory: "Classical / Film",
    description: "Dàn nhạc giao hưởng hoành tráng, giầu kịch tính và cảm xúc mênh mang.",
    instrumentation: ["chamber string quartet", "french horn harmony", "concert grand piano", "subtle timpani roll"],
    defaultTempoRange: [60, 110],
    moodKeywords: ["epic", "emotional", "dramatic", "spacious", "orchestral"],
  },
  {
    id: "pop",
    name: "Modern Pop",
    genreCategory: "Pop",
    description: "Nhịp điệu bắt tai, bass mượt, phím điện thoại gõ nhịp truyền cảm.",
    instrumentation: ["bright synth keys", "pluck synth", "punchy bassline", "modern pop drums"],
    defaultTempoRange: [100, 130],
    moodKeywords: ["catchy", "modern", "upbeat", "polished"],
  },
  {
    id: "rock",
    name: "Indie Rock / Alternative",
    genreCategory: "Rock",
    description: "Tiếng Guitar điện hòa âm dày dặn, nhịp trống dồn dập truyền năng lượng.",
    instrumentation: ["overdriven rhythm guitar", "solid electric bass", "acoustic drum kit", "ambient guitar feedback pad"],
    defaultTempoRange: [110, 150],
    moodKeywords: ["raw", "energetic", "driving", "authentic"],
  },
];
